name: 'Weekly Release'

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  monthly-release:
    runs-on: ubuntu-latest
    steps:

    # Clone repository
    - uses: actions/checkout@v4

    # Build your application, tool, artifacts, etc.
    - name: Build
      run: |
        pip install requests
        python split_bib.py

    # Update tag and pre-release
    # - Update (force-push) tag to the commit that is used in the workflow.
    # - Upload artifacts defined by the user.
    - name: Update Weekly release
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: weekly
        rm: true
        token: ${{ secrets.ACTIONS_SECRET }}
        files: |
          *.zip
